#!/usr/bin/env python3

from smartcard.System import readers

def main() -> int:
	print('List of available readers:')
	for i,r in enumerate(readers()):
		print('{0}: {1}'.format(i, r))
	return 0

if __name__ == '__main__':
	main()