#!/usr/bin/env python3

# Copyright 2023 Sergey Stolyarov <sergei@regolit.com>
#
# Distributed under New BSD License.
# 
# https://opensource.org/license/bsd-3-clause/

from smartcard.System import readers

def main() -> int:
	print('List of available readers:')
	for i,r in enumerate(readers()):
		print('{0}: {1}'.format(i, str(r)))
	return 0

if __name__ == '__main__':
	main()
